version: "3"
services:
  influxdb:
    image: influxdb:1.7
    restart: always
    environment:
      INFLUXDB_DB: benchmark
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    volumes:
      - ./influxdb:/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
      - "8083:8083"
  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
volumes:
  postgres:
