version: "3"
services:
  prisma:
    build: ../../
    restart: always
    depends_on:
      - db
      - influxdb
    ports:
      - "4466:4466"
    volumes:
      - ../prisma-service:/etc/datamodel
    environment:
      PRISMA_DML_PATH: /etc/datamodel/datamodel_postgres.prisma
      RUST_LOG: error
  db:
    image: timms/postgres-logging:10.3
    container_name: psql
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - ./chinook/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"
  influxdb:
    image: influxdb:1.7
    restart: always
    environment:
      INFLUXDB_DB: benchmark
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    volumes:
      - ./influxdb:/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
      - "8083:8083"
  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
volumes:
  postgres:
